# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book1',
        ),
    ]
